apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis
        image: redis:6
        ports:
        - containerPort: 6379
  volumeMounts:
  - name: redis-data
    mountPath: /data


---

apiVersion: v1
kind: Service
metadata:
  name: redis-slave-service
  namespace: redis
spec:
  selector:
    app: redis
    role: slave
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379