apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redis-slaves.opstergo.com
spec:
  group: opstergo.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: redisslaves
    singular: redisslave
    kind: RedisSlave
    shortNames:
      - rs
